import Footer from '@/(components)/Footer/Footer';
import Header from '@/(components)/Header/Header';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Catalog',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header title={ metadata.title} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
